services:
  - type: web
    name: realtime-notes-backend
    env: node
    plan: free
    buildCommand: npm ci --include=dev && npm run build
    startCommand: npm run prisma:deploy && npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://google-docs-example.vercel.app
      - key: FRONTEND_URLS
        value: http://localhost:3000,https://google-docs-example.vercel.app
      - key: BACKEND_PUBLIC_URL
        value: https://real-time-collaborative-notes-app-rxhf.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: realtime-notes-db
          property: connectionString
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: ACCESS_TOKEN_TTL
        value: 15m
      - key: REFRESH_TOKEN_TTL_DAYS
        value: 7

databases:
  - name: realtime-notes-db
    plan: free
    databaseName: realtime_notes
    user: realtime_notes_user
